# This is a basic workflow to help you get started with Actions

name: Botox

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  latest-build-release:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev
      - name: Build app
        run: pipenv run python setup.py py2app --resources resources
      - name: Archive Create
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'dist/Botox.app'
          filename: "Botox_Intel_${{ env.RELEASE_VERSION }}.zip"
          exclusions: '*.git* '
      - name: Archive Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Botox_Intel_${{ env.RELEASE_VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          allowUpdates: true
